CREATE TABLE PERMISSAO (
  idPermissao INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo VARCHAR(50) NOT NULL UNIQUE ,
  PRIMARY KEY(idPermissao)
);

CREATE TABLE TELA (
  idTela INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NULL UNIQUE ,
  PRIMARY KEY(idTela)
);

CREATE TABLE USUARIO (
  idUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL ,
  banco VARCHAR(50) NOT NULL ,
  conta VARCHAR(10) NOT NULL ,
  agencia VARCHAR(10) NOT NULL ,
  login VARCHAR(50) UNIQUE NOT NULL ,
  senha VARCHAR(50) NOT NULL ,
  dtCriacao DATETIME DEFAULT CURRENT_TIMESTAMP(),
  email VARCHAR(60) NULL UNIQUE ,
  PRIMARY KEY(idUsuario)
);

CREATE TABLE PERFIL (
  idPerfil INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  tipo VARCHAR(50) NULL UNIQUE ,
  PRIMARY KEY(idPerfil)
);

CREATE TABLE USUARIO_PERFIL (
  idUsuario INTEGER UNSIGNED NOT NULL,
  idPerfil INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idUsuario, idPerfil),
  FOREIGN KEY(idUsuario)
    REFERENCES USUARIO(idUsuario)
      ON DELETE CASCADE 
      ON UPDATE CASCADE,
  FOREIGN KEY(idPerfil)
    REFERENCES PERFIL(idPerfil)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE PERFIL_TELA (
  idPerfil INTEGER UNSIGNED NOT NULL,
  idTela INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idPerfil, idTela),
  FOREIGN KEY(idPerfil)
    REFERENCES PERFIL(idPerfil)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(idTela)
    REFERENCES TELA(idTela)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE PERFIL_TELA_PERMISSAO (
  idTela INTEGER UNSIGNED NOT NULL,
  idPerfil INTEGER UNSIGNED NOT NULL,
  idPermissao INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idTela, idPerfil, idPermissao),
  FOREIGN KEY(idPerfil, idTela)
    REFERENCES PERFIL_TELA(idPerfil, idTela)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(idPermissao)
    REFERENCES PERMISSAO(idPermissao)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);
# POPULAR DADOS TB_PERMISSAO
INSERT INTO PERMISSAO(tipo) VALUES('CREATE');
INSERT INTO PERMISSAO(tipo) VALUES('READ');
INSERT INTO PERMISSAO(tipo) VALUES('UPDATE');
INSERT INTO PERMISSAO(tipo) VALUES('DELETE');
INSERT INTO PERMISSAO(tipo) VALUES('DENIED');

/*
  DROP TABLE TB_PERFIL_TELA_PERMISSAO;
  DROP TABLE TB_PERFIL_TELA;
  DROP TABLE TB_USUARIO_PERFIL;
  DROP TABLE TB_PERFIL;
  DROP TABLE TB_USUARIO;
  DROP TABLE TB_TELA;
  DROP TABLE TB_PERMISSAO
*/
