DROP TABLE PERFIL_TELA_PERMISSAO;
DROP TABLE PERFIL_TELA;
DROP TABLE USUARIO_PERFIL;
DROP TABLE PERFIL;
DROP TABLE USUARIO;
DROP TABLE TELA;
DROP TABLE PERMISSAO;

CREATE TABLE Usuario (
  idUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL ,
  banco VARCHAR(50) NOT NULL ,
  conta VARCHAR(10) NOT NULL ,
  agencia VARCHAR(10) NOT NULL ,
  login VARCHAR(50) UNIQUE NOT NULL ,
  senha VARCHAR(50) NOT NULL ,
  dtCriacao DATETIME DEFAULT CURRENT_TIMESTAMP(),
  email VARCHAR(60) NULL UNIQUE ,
  PRIMARY KEY(idUsuario)
);

CREATE TABLE EnderecoUsuario (
  idUsuario INTEGER UNSIGNED NOT NULL,
  logradouro VARCHAR(100) NULL,
  numero INTEGER NULL,
  bairro VARCHAR(100) NULL,
  cidade VARCHAR(100) NULL,
  estado VARCHAR(100) NULL,
  cep VARCHAR(8) NULL,
  complemento VARCHAR(100) NULL,
  tipo VARCHAR(100) NULL,
  principal BIT NULL DEFAULT 0,
  PRIMARY KEY(idUsuario),
  FOREIGN KEY(idUsuario)
    REFERENCES Usuario(idUsuario)
      ON DELETE CASCADE
      ON UPDATE NO ACTION
);
